jobs:
- job: Linux_CPU_Build
  timeoutInMinutes: 120
  workspace:
    clean: all
  pool: Linux-CPU
  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - task: Docker@2
    displayName: login
    inputs:
      containerRegistry: onnxruntimeacrsvcconnection
      command: login
      addPipelineData: false
  - task: CmdLine@2
    inputs:
      script: |
        docker run --rm \
          --volume $(Build.SourcesDirectory):/onnxruntime_pytorch_src \
          -w /onnxruntime_pytorch_src \
          --env BUILD_ENVIRONMENT=pytorch-linux-xenial-py3.6-gcc5.4-ort \
          onnxtraining.azurecr.io/public/pytorch-eager-mode-ci:0.1 \
            bash -c "/onnxruntime_pytorch_src/.jenkins/pytorch/build.sh \
                      && /onnxruntime_pytorch_src/.jenkins/pytorch/test.sh"            
      workingDirectory: $(Build.SourcesDirectory)
  - task: Docker@2
    displayName: logout
    inputs:
      containerRegistry: onnxruntimeregistry
      command: logout
      addPipelineData: false

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()

